name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
permissions:

   contents: read

   pages: write

   id-token: write
concurrency:

   group: 'pages'

   cancel-in-progress: true
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run Unit Tests
      run: npx jest
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      if: always()
    - name: Run Playwright tests
      run: npx playwright test
      if: always()
    - name: combine test results
      run: mv integration-test-results test-results && mv unit-test-results/* test-results/
      if: always()
    - uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results
        retention-days: 30
    - uses: actions/upload-artifact@v4
      with:
        name: integration-test-report
        path: integration-test-report
        retention-days: 30
    - name: merge reports
      run: npx ctrf merge test-results --keep-reports --output merged-report.json
      if: always()
    - name: Publish CTRF Detailed Test Summary Results
      run: npx github-actions-ctrf tests test-results/merged-report.json
      if: always()
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Download test results
      uses: actions/download-artifact@v2
      with:
        name: integration-test-report

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v1

      with:

          # Upload the coverage directory from the repository

          path: './integration-test-report'
    - name: Deploy to GitHub Pages

      id: deployment

      uses: actions/deploy-pages@v1
    # - uses: actions/checkout@v4
    # - uses: actions/setup-node@v4
    #   with:
    #     node-version: lts/*
    # - name: Install dependencies
    #   run: npm ci
    # - name: Publish to NPM
    #   run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    # - name: Publish to GitHub Packages
    #   run: npm publish --access public
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Publish to GitHub Pages
    #   run: npm run build
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Deploy to GitHub Pages
    #   uses: actions/deploy-pages@v1
    #   with:
    #     branch: gh-pages
    #     folder: build
    #     token: ${{ secrets.GITHUB_TOKEN }}
